# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeNotificaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('model_type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('model_pk', models.IntegerField(help_text='Pk do objeto')),
            ],
            options={
                'verbose_name': 'Alterações',
                'verbose_name_plural': 'Alterações',
            },
        ),
        migrations.RemoveField(
            model_name='historicalcollect',
            name='catador',
        ),
        migrations.RemoveField(
            model_name='historicalcollect',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcollect',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='historicalpartner',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalphotobase',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalphotobase',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalphotocatador',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalphotocatador',
            name='catador',
        ),
        migrations.RemoveField(
            model_name='historicalphotocatador',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalphotocatador',
            name='photobase_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalphotocollectcatador',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalphotocollectcatador',
            name='coleta',
        ),
        migrations.RemoveField(
            model_name='historicalphotocollectcatador',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalphotocollectcatador',
            name='photobase_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalphotocollectuser',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalphotocollectuser',
            name='coleta',
        ),
        migrations.RemoveField(
            model_name='historicalphotocollectuser',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalphotocollectuser',
            name='photobase_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalphotocooperative',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalphotocooperative',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='historicalphotocooperative',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalphotocooperative',
            name='photobase_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalphotoresidue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalphotoresidue',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalphotoresidue',
            name='photobase_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalphotoresidue',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='historicalrating',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalrating',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalratingcatador',
            name='catador',
        ),
        migrations.RemoveField(
            model_name='historicalratingcatador',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalratingcatador',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='historicalratingcooperative',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='historicalratingcooperative',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalratingcooperative',
            name='rating',
        ),
        migrations.AddField(
            model_name='catador',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcatador',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='historicallatitudelongitude',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='historicalmobile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='latitudelongitude',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='material',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='photobase',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='rating',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='ratingcatador',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='ratingcooperative',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.DeleteModel(
            name='HistoricalCollect',
        ),
        migrations.DeleteModel(
            name='HistoricalPartner',
        ),
        migrations.DeleteModel(
            name='HistoricalPhotoBase',
        ),
        migrations.DeleteModel(
            name='HistoricalPhotoCatador',
        ),
        migrations.DeleteModel(
            name='HistoricalPhotoCollectCatador',
        ),
        migrations.DeleteModel(
            name='HistoricalPhotoCollectUser',
        ),
        migrations.DeleteModel(
            name='HistoricalPhotoCooperative',
        ),
        migrations.DeleteModel(
            name='HistoricalPhotoResidue',
        ),
        migrations.DeleteModel(
            name='HistoricalRating',
        ),
        migrations.DeleteModel(
            name='HistoricalRatingCatador',
        ),
        migrations.DeleteModel(
            name='HistoricalRatingCooperative',
        ),
    ]
